pybo/views/answer_views.py
from datetime import datetime

from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from pybo import db
from ..forms import AnswerForm
from pybo.models import Question, Answer

from pybo.views.auth_views import login_required


bp = Blueprint("answer", __name__, url_prefix='/answer/')


@bp.route('/create/<int:question_id>', methods=("post",))
@login_required
def create(question_id):
    # 댓글 달기
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    if form.validate_on_submit():
        content = request.form['content']
        answer = Answer(content=content, create_date=datetime.now(), user=g.user)
        question.answer_set.append(answer)
        db.session.commit()
        return redirect("{}#answer_{}".format(url_for('question.detail', question_id=question_id), answer.id))
    return render_template('question/question_detail.html', question=question, form=form)


@bp.route('/modify/<int:answer_id>', methods=('GET', 'POST'))
@login_required
def modify(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    if g.user != answer.user:
        flash("수정권한이 없습니다.")
        return redirect(url_for("question.detail", question_id=answer.question_id))
    if request.method == 'POST':
        form = AnswerForm();
        if form.validate_on_submit():
            form.populate_obj(answer)
            answer.modify_date = datetime.now()
            db.session.commit()
            return redirect(url_for('question.detail', question_id=answer.question_id))
    else:
        form = AnswerForm(obj=answer)
    return render_template('answer/answer_form.html', form=form)


@bp.route('/delete/<int:answer_id>')
@login_required
def delete(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    question_id = answer.question.id
    if g.user != answer.user:
        flash("삭제권한이 없습니다.")
    else:
        db.session.delete(answer)
        db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))

pybo/views/comment_view.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect

from pybo import db
from pybo.models import Question, Comment
from ..forms import CommentForm

from pybo.views.auth_views import login_required

bp = Blueprint('comment', __name__, url_prefix='/comment')


@bp.route('/create/question/<int:question_id>', methods=("GET", "POST"))
@login_required
def create_question(question_id):
    form = CommentForm()
    question = Question.query.get_or_404(question_id)
    if request.method == "POST" and form.validate_on_submit():
        comment = Comment(user=g.user, content=form.content.data, create_date=datetime.now(), question=question)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('question.detail', question_id=question_id))
    return render_template('comment/comment_form.html', form=form)


@bp.route('/modify/question/<int:comment_id>', methods=("GET", "POST"))
@login_required
def modify_question(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if g.user != comment.user:
        flash("수정권한이 없습니다.")
        return redirect(url_for("question.detail", question_id=comment.question.id))
    if request.method == "POST":
        form = CommentForm()
        if form.validate_on_submit():
            form.populate_obj(comment)
            comment.modify_date = datetime.now()
            db.session.commit()
            return redirect(url_for("question.detail", question_id=comment.question.id))
    else:
        form = CommentForm(obj=comment)
    return render_template("comment/comment_form.html", form=form)


@bp.route('/delete/question/<int:comment_id>')
@login_required
def delete_question(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    question_id = comment.question.id
    if g.user != comment.user:
        flash("수정권한이 없습니다.")
        return redirect(url_for("question.detail", question_id=question_id))
    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for("question.detail", question_id=question_id))

pybo/views/question_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect

from sqlalchemy import func

from pybo import db
from pybo.models import Question, Answer, User, question_voter
from ..forms import QuestionForm, AnswerForm

from pybo.views.auth_views import login_required

bp = Blueprint('question', __name__, url_prefix='/question')


@bp.route('/list/')
def _list():
    # 입력 파라미터
    page = request.args.get("page", type=int, default=1)
    kw = request.args.get("kw", type=str, default="")
    so = request.args.get("so", type=str, default="recent")

    #정렬
    if so == "recommend":
        sub_query = db.session.query(question_voter.c.question_id, func.count("*").label("num_voter")) \
            .group_by(question_voter.c.question_id).subquery()
        question_list = Question.query \
            .outerjoin(sub_query, Question.id == sub_query.c.question_id) \
            .order_by(sub_query.c.num_voter.desc(), Question.create_date.desc())
    elif so == "popular":
        sub_query = db.session.query(Answer.question_id, func.count('*').label('num_answer')) \
            .group_by(Answer.question_id).subquery()
        question_list = Question.query \
            .outerjoin(sub_query, Question.id == sub_query.c.question_id) \
            .order_by(sub_query.c.num_answer.desc(), Question.create_date.desc())
    else:   #recent
        question_list = Question.query.order_by(Question.create_date.desc())

    # 조회
    #question_list = Question.query.order_by(Question.create_date.desc())
    if kw:
        search = '%%{}%%'.format(kw)
        sub_query = db.session.query(Answer.question_id, Answer.content, User.userName).join(User, Answer.user_id == User.id).subquery()
        question_list = question_list.join(User).outerjoin(sub_query, sub_query.c.question_id == Question.id) \
                        .filter(Question.subject.ilike(search) |  # 질문제목
                                Question.content.ilike(search) |  # 질문내용
                                User.userName.ilike(search) |  # 질문작성자
                                sub_query.c.content.ilike(search) |  # 답변내용
                                sub_query.c.userName.ilike(search)  # 답변작성자
                                ) \
                        .distinct()
    # 페이징
    question_list = question_list.paginate(page, per_page=10)
    return render_template('question/question_list.html', question_list=question_list, page=page, kw=kw, so=so)


@bp.route('/detail/<int:question_id>')
def detail(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html', question=question, form=form)


@bp.route('/create/', methods=("get", "post"))
@login_required
def create():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        question = Question(subject=form.subject.data, content=form.content.data, create_date=datetime.now(), user=g.user)
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('question/question_form.html', form=form)


@bp.route('modify/<int:question_id>', methods=('GET', 'POST'))
@login_required
def modify(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('수정권한이 없습니다.')
        redirect(url_for('question.detail', question_id=question_id))
    if request.method == 'POST':
        form = QuestionForm()
        if form.validate_on_submit():
            form.populate_obj(question)
            question.modify_date = datetime.now()   # 수정일에 저장
            db.session.commit()
            return redirect(url_for('question.detail', question_id=question_id))
    else:
        form = QuestionForm(obj=question)
    return render_template('question/question_form.html', form=form)


@bp.route('delete/<int:question_id>', methods=("GET", "POST"))
@login_required
def delete(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash("삭제 권한이 없습니다.")
        return redirect(url_for("question.detail", question_id=question_id))
    db.session.delete(question)
    db.session.commit()
    return redirect(url_for("question._list"))

pybo/views/vote_view.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect

from pybo import db
from pybo.models import Question
from pybo.models import Answer
from ..forms import QuestionForm, AnswerForm

from pybo.views.auth_views import login_required


bp = Blueprint('vote', __name__, url_prefix='/vote')


@bp.route("/question/<int:question_id>")
@login_required
def question(question_id):

    _question = Question.query.get_or_404(question_id)
    if g.user == _question.user:
        flash('본인이 작성한 글은 추천할수 없습니다')
    else:
        _question.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))


@bp.route("/answer/<int:answer_id>/")
@login_required
def answer(answer_id):
    #import pdb; pdb.set_trace()
    _answer = Answer.query.get_or_404(answer_id)
    if g.user == _answer.user:
        flash("본인이 작성한 글은 추천할수 없습니다.")
    else:
        _answer.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('question.detail', question_id=_answer.question.id))

pybo/templates/question/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
	{% for message in get_flashed_messages() %}
	<div class="alert alert-danger" role="alert">{{message}}</div>
	{% endfor %}
	<h2 class="borer-bottom py-2">{{ question.subject }}</h2>
	<div class="row my-3">
        <div class="col-1"> <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{ question.voter|length }}</div>
            <a href="#" data-uri="{{ url_for('vote.question', question_id=question.id) }}" class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11"> <!-- 질문영역 -->
			<div class="card">
				<div class="card-body">
					<div class="card-text">{{ question.content | markdown }}</div>
					<div class="d-flex justify-content-end">
						<div class="badge badge-light p-2 text-left">
							<div class="mb-2">작성자 : {{ question.user.userName }}</div>
							<div>{{ question.create_date | datetime }}</div>
						</div>
						{% if question.modify_date %}
						<div class="badge badge-light p-2 text-left ml-1">
							<div class="mb-2">수정일</div>
							<div>{{ question.modify_date | datetime }}</div>
						</div>
						{% endif %}
					</div>
					{% if g.user == question.user%}
					<div class = "my-3" >
						<a href="{{ url_for('question.modify', question_id = question.id) }}" class="btn btn-sm btn-outline-secondary">수정</a>
						<a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{{ url_for('question.delete', question_id=question.id) }}">삭제</a>
					</div>
					{% endif %}

					<!-- 질문 댓글 start -->
					{% if question.comment_set|length > 0 %}
					<div class="mt-3">
					{% for comment in question.comment_set %}
						<div class="comment py-2 text-muted">
							<span style="white-space:pre-line;">{{comment.content}}</span>
							<span>
								- {{ comment.user.username }}, {{ comment.create_date|datetime}}
								{% if comment.modify_date %}
								(수정:{{ comment.modify_date|datetime }})
								{% endif %}
							</span>
							{% if g.user == comment.user %}
							<a href="{{ url_for('comment.modify_question', comment_id=comment.id) }}" class="small">수정</a>
							<a href="#" class="small delete" data-uri="{{ url_for('comment.delete_question', comment_id=comment.id) }}">삭제</a>
							{% endif %}
						</div>
					{% endfor %}
					</div>
					{% endif %}
					<div>
						<a href="{{ url_for('comment.create_question', question_id=question.id) }}" class="small"><small>댓글추가</small></a>
					</div>
					<!-- 질문 댓글 end -->
				</div>
			</div>
		</div>
	</div>

	<h5 class="border-bottom my-3 py-2">{{ question.answer_set|length }}개의 답변이 있습니다.</h5>
	{% for answer in question.answer_set %}
		<div class="row mb-3">
			<a id="answer_{{ answer.id }}"></a>
			<div class="col-1">
				<div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{ answer.voter|length }}</div>
				<a href="#" data-uri="{{ url_for('vote.answer', answer_id=answer.id) }}" class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
			</div>
			<div class="col-11">
				<div class="card">
					<div class="card-body">
						<div class="card-text">{{ answer.content | markdown }}</div>
						<div class="d-flex justify-content-end">
							<div class="badge badge-light p-2 text-left ">
								<div class="mb-2">작성자 : {{ answer.user.userName }}</div>
								<div>{{ answer.create_date | datetime  }}</div>
							</div>
							{% if answer.modify_date %}
								<div class="badge badge-light p-2 text-left ml-1">
									<div class="mb-2">수정일</div>
									<div>{{ answer.modify_date | datetime  }}</div>
								</div>
							{% endif %}
						</div>
						{% if g.user == answer.user %}
						<div class="my-3">
							<a href="{{ url_for('answer.modify', answer_id = answer.id) }}" class="btn btn-sm btn-outline-secondary">수정</a>
							<a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{{ url_for('answer.delete', answer_id=answer.id) }}">삭제</a>
						</div>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	{% endfor %}
	<form action="{{ url_for('answer.create', question_id=question.id) }}" method="post" class="my-3">
		{{ form.csrf_token }}
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
        </div>
        {% endfor %}
		<div class="form-group">
			<textarea {% if not g.user %} disabled {% endif %}class="form-control" name="content" id="content" rows="10"></textarea>
		</div>
		<input type="submit" value="답변등록" class="btn btn-primary">
	</form>
</div>
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });

    $(".recommend").on('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

pybo/templates/question/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {{ form.csrf_token }}
        <!-- 오류표시 Start -->
        {% include "form_errors.html" %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.data or '' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="5">{{ form.content.data or '' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>

    </form>
</div>

{% endblock %}

pybo/templates/question/question_form_auto.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">

        {{ form.subject.label }}
        {{ form.subject(class="form-control") }}

        {{ form.content.label }}
        {{ form.content(class="form-control") }}

        <button type="submit" class="btn btn-primary">저장하기</button>

    </form>
</div>

{% endblock %}

pybo/templates/question/question_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row justify-content-between my-3">
        <div class="col-2">
            <select class="form-control so">
                <option value="recent" {% if so =="recent" %} selected {% endif %}>최신순</option>
                <option value="recommend" {% if so =="recommend" %} selected {% endif %}>추천순</option>
                <option value="popular" {% if so =="popular" %} selected {% endif %}>인기순</option>
            </select>
        </div>
        <div class="col-4 input-group">
        <input type="text" class="form-control kw" value="{{ kr or '' }}">
        <div class="inpur-group-append">
            <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
        </div>
        </div>
    </div>
    <table class="table">
        <thead class="thead-dark">
            <th class="text-center">번호</th>
            <th class="text-center">추천</th>
            <th class="text-center" style="width:50%">제목</th>
            <th class="text-center">글쓴이</th>
            <th class="text-center">작성일시</th>
        </thead>
        <tbody>
            {% if question_list %}
            {% for question in question_list.items %}
                <tr class="text-center">
                    <td>{{ question_list.total - (question_list.page - 1) * question_list.per_page - loop.index0 }}</td>
                    <td>
                        {% if question.voter|length > 0 %}
                        <span class="badge badge-warning px-2 py-1">{{ question.voter|length}}</span>
                        {% endif %}
                    </td>
                    <td class="text-left">
                        <a href="{{ url_for('question.detail', question_id=question.id) }}">{{ question.subject }}</a>
                        {% if question.answer_set | length > 0 %}
                        <span class="text-danger small ml-2">{{ question.answer_set | length }}</span>
                        {% endif %}
                    </td>
                    <td>{{ question.user.userName }}</td>
                    <td>{{ question.create_date | datetime }}</td>
                </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">질문이 없습니다.</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
    <!--페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!--이전페이지-->
        {% if question_list.has_prev %}
        <li class="page-item">
            <a class="page-link" data-page="?page={{ question_list.prev_num }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        {% for page_num in question_list.iter_pages() %}
            {% if page_num %}
                {% if page_num != question_list.page %}
                <li class="page-item">
                    <a class="page-link" data-page="?page={{ page_num }}">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{ page_num }}</a>
                </li>
                {% endif %}
           {% else %}
                <li class="disabled">
                    <a class="page-link" href="#">...</a>
                </li>
           {% endif %}
        {% endfor %}
        <!-- 다음 페이지-->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="?page={{ question_list.next_num }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>

    <a href="{{ url_for('question.create') }}" class="btn btn-primary">질문 등록하기</a>
    <form id="searchForm" method="get" action="{{ url_for('question._list') }}">
        <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
        <input type="hidden" id="page" name="page" value="{{ page }}">
        <input type="hidden" id="so" name="so" value="{{ so }}">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
  $(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });

    $(".so").on("change", function(){
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
  });
</script>
{% endblock  %}